# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod ‘Firebase/Database'
target 'LuminousID' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LuminousID

  target 'LuminousIDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LuminousIDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
